#!/bin/sh

# A bootstrap script designed to be used in the virtual machine environment.

set -e

(cd / && \
	curl -LO https://arch.danirod.es/install.sh && \
	curl -LO https://arch.danirod.es/step_refind.sh && \
	chmod +x /install.sh /step_refind.sh)
PART_ROOT=/dev/vda2 PART_UEFI=/dev/vda1 PART_SWAP=/dev/vda3 /install.sh
/step_refind.sh
